### ISSUE TITLE
Display is great! -d doesn't work.

### ISSUE THREAD

**Issue by ryanpg123** [handsthatstrike/EpsLinNeo#1]
@handsthatstrike Hi there. I really appreciate your work on epslin! I was using the https://gist.github.com/asb2m10 version which works well, but the display is misaligned. Your fork looks perfect.

But, some functions seem to not work:

sudo ./epslin -d1 /dev/mmcblk0

Just produces the usage options, doesn't display any info.

The -D flag correctly displays the image content.

```
sudo ./epslin -D /dev/mmcblk0 
Ensoniq EPS/ASR Directory and Disk Information 

------------------------------------------+---------------------------------+
 Disk Label: DISK000                      | FILE: mmcblk0                   |
------+----------+--------------+---------+------------------+--------------+
  Idx |Type      | Name         |Blocks   | FileName         | FileSize     |
------+----------+--------------+---------+------------------+--------------+
   00 | E16-OS   | EPS-16+ O.S. |     167 | EPS-16+ O.S..efe |        86016 |
   01 | DIR/     | SOUNDS       |         |                  |              |
   02 | DIR/     | BANKS        |         |                  |              |
   03 | DIR/     | SEQUENCES    |         |                  |              |
   04 | DIR/     | SYSEX FILES  |         |                  |              |
   05 | EPS-Mac  | MACROFILE  1 |       1 | MACROFILE  1.efe |         1024 |
------+----------+--------------+---------+---------------------------------+
 Used:                      188 Blocks    |  Used:            96256 Bytes   |
 Free:                  3819253 Blocks    |  Free:       1955457536 Bytes   |
----------------------------------------------------------------------------+
```

**Comment by handsthatstrike** [comment]
"sudo ./epslin -d1 /dev/mmcblk0" just specifies what device and directory to use. It isn't telling EpsLin to actually *do* anything. There needs to be some type of specified action for directory 1 on mmcblk0, such as get all EFEs.

Maybe you're trying to do "sudo ./epslin -d1 -D /dev/mmcblk0" which will list directory 1.

**Comment by ryanpg123** [comment]
Thank you for your response. In the help file -d alone reads the directory.

Example: Reading CD-ROM "STRINGED"-directory (Index path 1) content

C:\EpsLin>epslin -d1 /dev/scd0

------------------------------------------+---------------------------------+
 Disk Label: CDRM001                      | PIANO+ORGAN
|
------+----------+--------------+---------+------------------+--------------+
  Idx |Type      | Name         |Blocks   | FileName         | FileSize
|
------+----------+--------------+---------+------------------+--------------+
   00 | .. /     | ROOT         |         |                  |
|
   01 | DIR/     | STRING SECTN |         |                  |
|
   02 | DIR/     | SOLO STRING  |         |                  |
|
   03 | DIR/     | ACOUSTC GUIT |         |                  |
|
   04 | DIR/     | ELEC GUITAR  |         |                  |
|
   05 | DIR/     | HARP         |         |                  |
|
   06 | DIR/     | HARPSI+CLAV  |         |                  |
|
   07 | DIR/     | COUNTRY+WEST |         |                  |
|
   08 | DIR/     | ORIENTAL     |         |                  |
|
   09 | DIR/     | ETHNIC+MISC  |         |                  |
|
------+----------+--------------+---------+---------------------------------+
 Used:                   255370 Blocks    |  Used:        130749440 Bytes
|
 Free:                   438117 Blocks    |  Free:        224315904 Bytes
|
----------------------------------------------------------------------------+

I am able to get a file as you describe, for example: "./epslin -d2 -g1
epsscsi.img" pulls the first file from directory 02.

Now that you've explained it I see that: "./epslin -d2 -D
epsscsi.img" correctly lists the contents of directories.

I'll play around and keep notes on some of the minor differences between
your version and the official help file.

Thanks again for your work on this!

Oh, btw, I found another really cool project that might be of interest to
you. It allows you to browse an ASR or EPS disk or image in a way similar
to FTP and use linux-like file management commands. I created a github repo
(with the author's permission). Check it out if you're inclined!

https://github.com/ryanpg123/asr10

Ryan

"Reality is that which, when you stop believing in it, doesn’t go away."
-Philip K. Dick
